In [5]:
import pandas as pd
df=pd.read_csv('pandayday1\emp1.csv')

In [6]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.00      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.89      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.90      20  2021-07-22

In [7]:
df_eno_ename=pd.read_csv('pandayday1\emp1.csv',usecols=['eno','ename'])

In [8]:
df1=pd.read_csv('pandayday1\emp1.csv',usecols=['eno'])

In [9]:
type(df1)

pandas.core.frame.DataFrame

In [10]:
type(df_eno_ename)

pandas.core.frame.DataFrame

In [11]:
df1=pd.read_csv('pandayday1\emp1.csv',usecols=['eno'])

In [12]:
df1

    eno
0    10
1     2
2     8
3     4
4     5
5     6
6     7
7     3
8     9
9     1
10   11
11   12
12   13
13   14
14   15

In [13]:
df1=pd.read_csv('pandayday1\emp1.csv')

In [14]:
df1['eno']

0     10
1      2
2      8
3      4
4      5
5      6
6      7
7      3
8      9
9      1
10    11
11    12
12    13
13    14
14    15
Name: eno, dtype: int64

In [15]:
type(df1)

pandas.core.frame.DataFrame

In [16]:
df_eno_ename[['eno','ename']]

    eno   ename
0    10   Amber
1     2    Amar
2     8   Sagar
3     4  Thomas
4     5    Jade
5     6   Smith
6     7  Robert
7     3    Nick
8     9   Naman
9     1   Vikas
10   11  Dennis
11   12   Karan
12   13  Simran
13   14    Amit
14   15    Neha

In [17]:
type(df_eno_ename)

pandas.core.frame.DataFrame

In [18]:
df.dtypes

eno         int64
ename      object
salary    float64
deptno      int64
doj        object
dtype: object

In [19]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.00      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.89      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.90      20  2021-07-22

In [20]:
df.dtypes

eno         int64
ename      object
salary    float64
deptno      int64
doj        object
dtype: object

In [21]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.00      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.89      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.90      20  2021-07-22

In [22]:
df=pd.read_csv('pandayday1\emp1.csv',parse_dates=['doj'])

In [23]:
df

    eno   ename    salary  deptno        doj
0    10   Amber   1000.00      10 2018-05-14
1     2    Amar   1000.00      10 2017-03-22
2     8   Sagar   1000.00      20 2020-11-30
3     4  Thomas   1000.00      10 2019-08-18
4     5    Jade   2000.00      10 2021-02-10
5     6   Smith   1000.00      10 2016-12-01
6     7  Robert   3000.00      20 2023-06-25
7     3    Nick   1000.00      30 2015-09-15
8     9   Naman   4000.00      30 2020-01-20
9     1   Vikas   1000.00      30 2017-10-03
10   11  Dennis  41000.00      20 2024-01-05
11   12   Karan   2200.00      20 2018-06-16
12   13  Simran   1500.89      10 2019-12-19
13   14    Amit   2000.00      30 2022-04-09
14   15    Neha   1700.90      20 2021-07-22

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df.dtypes

eno                int64
ename             object
salary           float64
deptno             int64
doj       datetime64[ns]
dtype: object

In [26]:
df['doj']

0    2018-05-14
1    2017-03-22
2    2020-11-30
3    2019-08-18
4    2021-02-10
5    2016-12-01
6    2023-06-25
7    2015-09-15
8    2020-01-20
9    2017-10-03
10   2024-01-05
11   2018-06-16
12   2019-12-19
13   2022-04-09
14   2021-07-22
Name: doj, dtype: datetime64[ns]

In [27]:
df['doj'].dt.year

0     2018
1     2017
2     2020
3     2019
4     2021
5     2016
6     2023
7     2015
8     2020
9     2017
10    2024
11    2018
12    2019
13    2022
14    2021
Name: doj, dtype: int64

In [28]:
df['doj'].dt.day

0     14
1     22
2     30
3     18
4     10
5      1
6     25
7     15
8     20
9      3
10     5
11    16
12    19
13     9
14    22
Name: doj, dtype: int64

In [29]:
df['doj'].dt.month

0      5
1      3
2     11
3      8
4      2
5     12
6      6
7      9
8      1
9     10
10     1
11     6
12    12
13     4
14     7
Name: doj, dtype: int64

In [30]:
df=pd.read_csv('pandayday1\emp1.csv',parse_dates=['doj'],dtype={'eno':float})

In [31]:
df

     eno   ename    salary  deptno        doj
0   10.0   Amber   1000.00      10 2018-05-14
1    2.0    Amar   1000.00      10 2017-03-22
2    8.0   Sagar   1000.00      20 2020-11-30
3    4.0  Thomas   1000.00      10 2019-08-18
4    5.0    Jade   2000.00      10 2021-02-10
5    6.0   Smith   1000.00      10 2016-12-01
6    7.0  Robert   3000.00      20 2023-06-25
7    3.0    Nick   1000.00      30 2015-09-15
8    9.0   Naman   4000.00      30 2020-01-20
9    1.0   Vikas   1000.00      30 2017-10-03
10  11.0  Dennis  41000.00      20 2024-01-05
11  12.0   Karan   2200.00      20 2018-06-16
12  13.0  Simran   1500.89      10 2019-12-19
13  14.0    Amit   2000.00      30 2022-04-09
14  15.0    Neha   1700.90      20 2021-07-22

In [32]:
df.dtypes

eno              float64
ename             object
salary           float64
deptno             int64
doj       datetime64[ns]
dtype: object

In [33]:
type(df['doj'])

pandas.core.series.Series

In [34]:
df['doj'].dtypes

dtype('<M8[ns]')

In [35]:
df.dtypes

eno              float64
ename             object
salary           float64
deptno             int64
doj       datetime64[ns]
dtype: object

In [36]:
df.iloc[1]

eno                       2.0
ename                    Amar
salary                 1000.0
deptno                     10
doj       2017-03-22 00:00:00
Name: 1, dtype: object

In [37]:
df.iloc[3]

eno                       4.0
ename                  Thomas
salary                 1000.0
deptno                     10
doj       2019-08-18 00:00:00
Name: 3, dtype: object

In [38]:
df.iloc[1:3]

   eno  ename  salary  deptno        doj
1  2.0   Amar  1000.0      10 2017-03-22
2  8.0  Sagar  1000.0      20 2020-11-30

In [39]:
df.iloc[1:]

     eno   ename    salary  deptno        doj
1    2.0    Amar   1000.00      10 2017-03-22
2    8.0   Sagar   1000.00      20 2020-11-30
3    4.0  Thomas   1000.00      10 2019-08-18
4    5.0    Jade   2000.00      10 2021-02-10
5    6.0   Smith   1000.00      10 2016-12-01
6    7.0  Robert   3000.00      20 2023-06-25
7    3.0    Nick   1000.00      30 2015-09-15
8    9.0   Naman   4000.00      30 2020-01-20
9    1.0   Vikas   1000.00      30 2017-10-03
10  11.0  Dennis  41000.00      20 2024-01-05
11  12.0   Karan   2200.00      20 2018-06-16
12  13.0  Simran   1500.89      10 2019-12-19
13  14.0    Amit   2000.00      30 2022-04-09
14  15.0    Neha   1700.90      20 2021-07-22

In [40]:
df.iloc[0:]

     eno   ename    salary  deptno        doj
0   10.0   Amber   1000.00      10 2018-05-14
1    2.0    Amar   1000.00      10 2017-03-22
2    8.0   Sagar   1000.00      20 2020-11-30
3    4.0  Thomas   1000.00      10 2019-08-18
4    5.0    Jade   2000.00      10 2021-02-10
5    6.0   Smith   1000.00      10 2016-12-01
6    7.0  Robert   3000.00      20 2023-06-25
7    3.0    Nick   1000.00      30 2015-09-15
8    9.0   Naman   4000.00      30 2020-01-20
9    1.0   Vikas   1000.00      30 2017-10-03
10  11.0  Dennis  41000.00      20 2024-01-05
11  12.0   Karan   2200.00      20 2018-06-16
12  13.0  Simran   1500.89      10 2019-12-19
13  14.0    Amit   2000.00      30 2022-04-09
14  15.0    Neha   1700.90      20 2021-07-22

In [41]:
df.iloc[5:9]

   eno   ename  salary  deptno        doj
5  6.0   Smith  1000.0      10 2016-12-01
6  7.0  Robert  3000.0      20 2023-06-25
7  3.0    Nick  1000.0      30 2015-09-15
8  9.0   Naman  4000.0      30 2020-01-20

In [42]:
df.iloc[1:9:2]

   eno   ename  salary  deptno        doj
1  2.0    Amar  1000.0      10 2017-03-22
3  4.0  Thomas  1000.0      10 2019-08-18
5  6.0   Smith  1000.0      10 2016-12-01
7  3.0    Nick  1000.0      30 2015-09-15

In [43]:
df=pd.read_csv('pandayday1\emp1.csv',skiprows=range(1,6),nrows=5)

In [44]:
df

   eno   ename  salary  deptno         doj
0    6   Smith    1000      10  2016-12-01
1    7  Robert    3000      20  2023-06-25
2    3    Nick    1000      30  2015-09-15
3    9   Naman    4000      30  2020-01-20
4    1   Vikas    1000      30  2017-10-03

In [45]:
df=pd.read_csv('pandayday1\emp1.csv',delimiter=',')

In [46]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.00      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.89      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.90      20  2021-07-22

In [51]:
df=pd.read_csv('pandayday1\emp2.csv',delimiter=';')

In [52]:
df

                           eno  ename  salary  deptno         doj
0                           10  Amber  1000.0    10.0  2018-05-14
1                            2   Amar  1000.0    10.0  2017-03-22
2                            8  Sagar  1000.0    20.0  2020-11-30
3  4,Thomas,1000,10,2019-08-18    NaN     NaN     NaN         NaN

In [54]:
df=pd.read_csv('pandayday1\emp2.csv.gz',compression='gzip')

FileNotFoundError: [Errno 2] No such file or directory: 'pandayday1\\emp2.csv.gz'

In [55]:
for cnk in pd.read_csv('emp.csv',chunksize=5):
    print(cnk)

   eno   ename   salary  deptno         doj
0   10   Amber  1000.56      10  2018-05-14
1    2    Amar  1000.00      10  2017-03-22
2    8   Sagar  1000.00      20  2020-11-30
3    4  Thomas  1000.00      10  2019-08-18
4    5    Jade  2000.00      10  2021-02-10
   eno   ename   salary  deptno         doj
5    6   Smith  1000.00      10  2016-12-01
6    7  Robert  3000.00      20  2023-06-25
7    3    Nick  1000.89      30  2015-09-15
8    9   Naman  4000.00      30  2020-01-20
9    1   Vikas  1000.00      30  2017-10-03
    eno   ename  salary  deptno         doj
10   11  Dennis   41000      20  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22

In [56]:
for cnk in pd.read_csv('emp.csv'):
    print(cnk)

eno
ename
salary
deptno
doj

In [59]:
df=pd.read_csv('emp.csv',low_memory='True')
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22

In [60]:
df=pd.read_csv('emp.csv',low_memory='False')
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22