In [1]:
import pandas as pd

In [2]:
pd.read_csv('emp.csv')

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  2018-05-14
1     2    Amar    1000      10  2017-03-22
2     8   Sagar    1000      20  2020-11-30
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-02-10
5     6   Smith    1000      10  2016-12-01
6     7  Robert    3000      20  2023-06-25
7     3    Nick    1000      30  2015-09-15
8     9   Naman    4000      30  2020-01-20
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      20  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22

In [4]:
df=pd.read_csv('pandayday1/emp1.csv')

In [5]:
df

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  2018-05-14
1     2    Amar    1000      10  2017-03-22
2     8   Sagar    1000      20  2020-11-30
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-02-10
5     6   Smith    1000      10  2016-12-01
6     7  Robert    3000      20  2023-06-25
7     3    Nick    1000      30  2015-09-15
8     9   Naman    4000      30  2020-01-20
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      20  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22

In [6]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df=pd.read_csv('pandayday1/emp1.csv',usecols=['eno','ename'])

In [9]:
df

    eno   ename
0    10   Amber
1     2    Amar
2     8   Sagar
3     4  Thomas
4     5    Jade
5     6   Smith
6     7  Robert
7     3    Nick
8     9   Naman
9     1   Vikas
10   11  Dennis
11   12   Karan
12   13  Simran
13   14    Amit
14   15    Neha