In [1]:
import pandas as pd

In [17]:
df=pd.read_csv('emp.csv')

In [18]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22

In [48]:
dept_no10=(df['deptno']==10) | (df['deptno']==20)

In [36]:
sal_1000=df['salary']<2000

In [38]:
Filter_dept=dept_no10 & sal_1000

In [41]:
Filter_dept_sal
type(Filter_dept_sal)

pandas.core.series.Series

In [40]:
df[Filter_dept_sal]

    eno   ename   salary  deptno         doj
0    10   Amber  1000.56      10  2018-05-14
1     2    Amar  1000.00      10  2017-03-22
3     4  Thomas  1000.00      10  2019-08-18
5     6   Smith  1000.00      10  2016-12-01
12   13  Simran  1500.00      10  2019-12-19

In [42]:
type(df[Filter_dept_sal])

pandas.core.frame.DataFrame

In [45]:
df[(df['deptno']==10) & (df['salary']<2000)]

    eno   ename   salary  deptno         doj
0    10   Amber  1000.56      10  2018-05-14
1     2    Amar  1000.00      10  2017-03-22
3     4  Thomas  1000.00      10  2019-08-18
5     6   Smith  1000.00      10  2016-12-01
12   13  Simran  1500.00      10  2019-12-19

In [49]:
a=df['deptno']==10
b=df['deptno']==20
c=a|b

In [50]:
df[c]

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
14   15    Neha   1700.00      20  2021-07-22

In [53]:
#dept other than 10 or 20
d= ~c

In [54]:
df[d]

    eno  ename   salary  deptno         doj
7     3   Nick  1000.89      30  2015-09-15
8     9  Naman  4000.00      30  2020-01-20
9     1  Vikas  1000.00      30  2017-10-03
13   14   Amit  2000.00      30  2022-04-09

In [55]:
#sorting
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22

In [56]:
df.sort_values(by='deptno')

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
12   13  Simran   1500.00      10  2019-12-19
2     8   Sagar   1000.00      20  2020-11-30
6     7  Robert   3000.00      20  2023-06-25
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
14   15    Neha   1700.00      20  2021-07-22
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
13   14    Amit   2000.00      30  2022-04-09

In [57]:
df.sort_values(by='deptno',ascending=True)

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
12   13  Simran   1500.00      10  2019-12-19
2     8   Sagar   1000.00      20  2020-11-30
6     7  Robert   3000.00      20  2023-06-25
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
14   15    Neha   1700.00      20  2021-07-22
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
13   14    Amit   2000.00      30  2022-04-09

In [59]:
df.sort_values(by='deptno',ascending=False)

    eno   ename    salary  deptno         doj
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
13   14    Amit   2000.00      30  2022-04-09
2     8   Sagar   1000.00      20  2020-11-30
6     7  Robert   3000.00      20  2023-06-25
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
14   15    Neha   1700.00      20  2021-07-22
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
12   13  Simran   1500.00      10  2019-12-19

In [60]:
df.sort_values(by=['deptno','salary'],ascending=[True,False])

    eno   ename    salary  deptno         doj
4     5    Jade   2000.00      10  2021-02-10
12   13  Simran   1500.00      10  2019-12-19
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
3     4  Thomas   1000.00      10  2019-08-18
5     6   Smith   1000.00      10  2016-12-01
10   11  Dennis  41000.00      20  2024-01-05
6     7  Robert   3000.00      20  2023-06-25
11   12   Karan   2200.00      20  2018-06-16
14   15    Neha   1700.00      20  2021-07-22
2     8   Sagar   1000.00      20  2020-11-30
8     9   Naman   4000.00      30  2020-01-20
13   14    Amit   2000.00      30  2022-04-09
7     3    Nick   1000.89      30  2015-09-15
9     1   Vikas   1000.00      30  2017-10-03

In [61]:
df.sort_values(by=['deptno','salary'],ascending=[True,False],inplace=True)

In [62]:
df

    eno   ename    salary  deptno         doj
4     5    Jade   2000.00      10  2021-02-10
12   13  Simran   1500.00      10  2019-12-19
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
3     4  Thomas   1000.00      10  2019-08-18
5     6   Smith   1000.00      10  2016-12-01
10   11  Dennis  41000.00      20  2024-01-05
6     7  Robert   3000.00      20  2023-06-25
11   12   Karan   2200.00      20  2018-06-16
14   15    Neha   1700.00      20  2021-07-22
2     8   Sagar   1000.00      20  2020-11-30
8     9   Naman   4000.00      30  2020-01-20
13   14    Amit   2000.00      30  2022-04-09
7     3    Nick   1000.89      30  2015-09-15
9     1   Vikas   1000.00      30  2017-10-03

In [63]:
df.sort_index()

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22

In [64]:
df.sort_index(ascending=False)

    eno   ename    salary  deptno         doj
14   15    Neha   1700.00      20  2021-07-22
13   14    Amit   2000.00      30  2022-04-09
12   13  Simran   1500.00      10  2019-12-19
11   12   Karan   2200.00      20  2018-06-16
10   11  Dennis  41000.00      20  2024-01-05
9     1   Vikas   1000.00      30  2017-10-03
8     9   Naman   4000.00      30  2020-01-20
7     3    Nick   1000.89      30  2015-09-15
6     7  Robert   3000.00      20  2023-06-25
5     6   Smith   1000.00      10  2016-12-01
4     5    Jade   2000.00      10  2021-02-10
3     4  Thomas   1000.00      10  2019-08-18
2     8   Sagar   1000.00      20  2020-11-30
1     2    Amar   1000.00      10  2017-03-22
0    10   Amber   1000.56      10  2018-05-14

In [65]:
df.sort_values(by=['deptno','salary'],ascending=[True,False],inplace=True)

In [68]:
df

    eno   ename    salary  deptno         doj
4     5    Jade   2000.00      10  2021-02-10
12   13  Simran   1500.00      10  2019-12-19
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
3     4  Thomas   1000.00      10  2019-08-18
5     6   Smith   1000.00      10  2016-12-01
10   11  Dennis  41000.00      20  2024-01-05
6     7  Robert   3000.00      20  2023-06-25
11   12   Karan   2200.00      20  2018-06-16
14   15    Neha   1700.00      20  2021-07-22
2     8   Sagar   1000.00      20  2020-11-30
8     9   Naman   4000.00      30  2020-01-20
13   14    Amit   2000.00      30  2022-04-09
7     3    Nick   1000.89      30  2015-09-15
9     1   Vikas   1000.00      30  2017-10-03

In [69]:
df=pd.read_csv('emp.csv')

In [70]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22

In [71]:
df.groupby('deptno')['salary'].sum()

deptno
10     7500.56
20    48900.00
30     8000.89
Name: salary, dtype: float64

In [72]:
df2=df.groupby('deptno')['salary'].sum()

In [77]:
type(df2)

pandas.core.series.Series

In [81]:
df3=df2.reset_index()

In [82]:
df3.rename(columns={'salary':'Total_sal'})

   deptno  Total_sal
0      10    7500.56
1      20   48900.00
2      30    8000.89

In [83]:
df.groupby('deptno')['salary'].sum().reset_index().rename(columns={'salary':'Total_sal'})

   deptno  Total_sal
0      10    7500.56
1      20   48900.00
2      30    8000.89

In [84]:
df.groupby('deptno',as_index=False)['salary'].sum().rename(columns={'salary':'Total_sal'})

   deptno  Total_sal
0      10    7500.56
1      20   48900.00
2      30    8000.89

In [101]:
df_count=df.groupby('deptno',as_index=False)['eno'].count().rename(columns={'eno':'Total_count'})

In [102]:
df_count1=df.groupby('deptno',as_index=False)['eno'].count()

In [110]:
re_name={'eno':'Total_Eno'}
df_updated=df_count1.rename(columns=re_name)

In [111]:
df_updated

   deptno  Total_Eno
0      10          6
1      20          5
2      30          4

In [112]:
df_updated.sort_values(by='deptno',ascending=False,inplace=True)

In [113]:
df_updated

   deptno  Total_Eno
2      30          4
1      20          5
0      10          6

In [114]:
df.groupby(['deptno','salary'],as_index=False)['eno'].count().rename(columns={'eno':'Total_count'})

    deptno    salary  Total_count
0       10   1000.00            3
1       10   1000.56            1
2       10   1500.00            1
3       10   2000.00            1
4       20   1000.00            1
5       20   1700.00            1
6       20   2200.00            1
7       20   3000.00            1
8       20  41000.00            1
9       30   1000.00            1
10      30   1000.89            1
11      30   2000.00            1
12      30   4000.00            1

In [118]:
df.groupby('deptno')['salary'].agg(['min','max','sum','count']).reset_index().rename(columns={'min':'MIN_SAL','max':'MAX_SAL','sum':'TOT_SAL','count':'Count_ENO'})

   deptno  MIN_SAL  MAX_SAL   TOT_SAL  Count_ENO
0      10   1000.0   2000.0   7500.56          6
1      20   1000.0  41000.0  48900.00          5
2      30   1000.0   4000.0   8000.89          4

In [122]:
df_dept_sal=df.groupby('deptno',as_index=False)['salary'].sum().rename(columns={'salary':'total_sal'})

In [123]:
df_dept_sal

   deptno  total_sal
0      10    7500.56
1      20   48900.00
2      30    8000.89

In [130]:
status=df_dept_sal.apply(lambda x:x>10000)

In [129]:
type(df_dept_sal)

pandas.core.frame.DataFrame

In [131]:
type(status)

pandas.core.frame.DataFrame

In [132]:
status

   deptno  total_sal
0   False      False
1   False       True
2   False      False

In [135]:
a=status['total_sal']

In [136]:
type(a)

pandas.core.series.Series

In [138]:
df_dept_sal[a]

   deptno  total_sal
1      20    48900.0

In [139]:
type(df_dept_sal[a])

pandas.core.frame.DataFrame

In [141]:
df=pd.read_csv('emp.csv')

In [142]:
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.56      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4     5    Jade   2000.00      10  2021-02-10
5     6   Smith   1000.00      10  2016-12-01
6     7  Robert   3000.00      20  2023-06-25
7     3    Nick   1000.89      30  2015-09-15
8     9   Naman   4000.00      30  2020-01-20
9     1   Vikas   1000.00      30  2017-10-03
10   11  Dennis  41000.00      20  2024-01-05
11   12   Karan   2200.00      20  2018-06-16
12   13  Simran   1500.00      10  2019-12-19
13   14    Amit   2000.00      30  2022-04-09
14   15    Neha   1700.00      20  2021-07-22

In [146]:
df2=pd.read_csv('pandayday1\dept.csv')

In [147]:
df2

   deptno   deptname
0      10         HR
1      20  chemistry
2      30    Physics

In [149]:
df.merge(df2,on='deptno',how='inner')

    eno   ename    salary  deptno         doj   deptname
0    10   Amber   1000.56      10  2018-05-14         HR
1     2    Amar   1000.00      10  2017-03-22         HR
2     4  Thomas   1000.00      10  2019-08-18         HR
3     5    Jade   2000.00      10  2021-02-10         HR
4     6   Smith   1000.00      10  2016-12-01         HR
5    13  Simran   1500.00      10  2019-12-19         HR
6     8   Sagar   1000.00      20  2020-11-30  chemistry
7     7  Robert   3000.00      20  2023-06-25  chemistry
8    11  Dennis  41000.00      20  2024-01-05  chemistry
9    12   Karan   2200.00      20  2018-06-16  chemistry
10   15    Neha   1700.00      20  2021-07-22  chemistry
11    3    Nick   1000.89      30  2015-09-15    Physics
12    9   Naman   4000.00      30  2020-01-20    Physics
13    1   Vikas   1000.00      30  2017-10-03    Physics
14   14    Amit   2000.00      30  2022-04-09    Physics

In [151]:
df1=pd.read_csv('pandayday1\dept1.csv')

In [152]:
df1

   deptno1   deptname
0       10         HR
1       20  chemistry
2       30    Physics

In [157]:
df3=df.merge(df1,left_on='deptno',right_on='deptno1',how='inner')

In [158]:
rq1=['eno','deptno','ename','salary']

In [159]:
df3[rq1]

    eno  deptno   ename    salary
0    10      10   Amber   1000.56
1     2      10    Amar   1000.00
2     4      10  Thomas   1000.00
3     5      10    Jade   2000.00
4     6      10   Smith   1000.00
5    13      10  Simran   1500.00
6     8      20   Sagar   1000.00
7     7      20  Robert   3000.00
8    11      20  Dennis  41000.00
9    12      20   Karan   2200.00
10   15      20    Neha   1700.00
11    3      30    Nick   1000.89
12    9      30   Naman   4000.00
13    1      30   Vikas   1000.00
14   14      30    Amit   2000.00