In [2]:
import pandas as pd

In [3]:
df_emp=pd.read_csv('pandayday1\emp1.csv')
df_emp

<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
<>:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_5324\1765266088.py:1: SyntaxWarning: "\e" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\e"? A raw string is also an option.
  df_emp=pd.read_csv('pandayday1\emp1.csv')

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4    10   Amber   1000.00      10  2018-05-14
5     2    Amar   1000.00      10  2017-03-22
6     8   Sagar   1000.00      20  2020-11-30
7     4  Thomas   1000.00      10  2019-08-18
8     5    Jade   2000.00      10  2021-02-10
9     6   Smith   1000.00      10  2016-12-01
10    7  Robert   3000.00      20  2023-06-25
11    3    Nick   1000.00      30  2015-09-15
12    9   Naman   4000.00      30  2020-01-20
13    1   Vikas   1000.00      30  2017-10-03
14   11  Dennis  41000.00      20  2024-01-05
15   12   Karan   2200.00      20  2018-06-16
16   13  Simran   1500.89      10  2019-12-19
17   14    Amit   2000.00      30  2022-04-09
18   15    Neha   1700.90      20  2021-07-22

In [4]:
df_Sal=pd.read_csv('pandayday1\salary.csv')

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_5324\421543973.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df_Sal=pd.read_csv('pandayday1\salary.csv')

In [5]:
df_emp.merge(df_Sal,left_on='eno',right_on='eno1',how='inner')

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,10,Amber,1000.0,10,2018-05-14,10,Amber,1000,10,2018-05-14
1,2,Amar,1000.0,10,2017-03-22,2,Amar,1000,10,2017-03-22
2,8,Sagar,1000.0,20,2020-11-30,8,Sagar,1000,20,2020-11-30
3,4,Thomas,1000.0,10,2019-08-18,4,Thomas,1000,10,2019-08-18
4,10,Amber,1000.0,10,2018-05-14,10,Amber,1000,10,2018-05-14
5,2,Amar,1000.0,10,2017-03-22,2,Amar,1000,10,2017-03-22
6,8,Sagar,1000.0,20,2020-11-30,8,Sagar,1000,20,2020-11-30
7,4,Thomas,1000.0,10,2019-08-18,4,Thomas,1000,10,2019-08-18

In [6]:
df_left=df_emp.merge(df_Sal,left_on='eno',right_on='eno1',how='left')
df_left

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,10,Amber,1000.00,10,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
1,2,Amar,1000.00,10,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
2,8,Sagar,1000.00,20,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
3,4,Thomas,1000.00,10,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
4,10,Amber,1000.00,10,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
5,2,Amar,1000.00,10,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
6,8,Sagar,1000.00,20,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
7,4,Thomas,1000.00,10,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
8,5,Jade,2000.00,10,2021-02-10,NaN,NaN,NaN,NaN,NaN
9,6,Smith,1000.00,10,2016-12-01,NaN,NaN,NaN,NaN,NaN
10,7,Robert,3000.00,20,2023-06-25,NaN,NaN,NaN,NaN,NaN
11,3,Nick,1000.00,30,2015-09-15,NaN,NaN,NaN,NaN,NaN
12,9,Naman,4000.00,30,2020-01-20,NaN,NaN,NaN,NaN,NaN
13,1,Vikas,1000.00,30,2017-10-03,NaN,NaN,NaN,NaN,NaN
14,11,Dennis,41000.00,20,2024-01-05,NaN,NaN,NaN,NaN,NaN
15,12,Karan,2200.00,20,2018-06-16,NaN,NaN,NaN,NaN,NaN
16,13,Simran,1500.89,10,2019-12-19,NaN,NaN,NaN,NaN,NaN
17,14,Amit,2000.00,30,2022-04-09,NaN,NaN,NaN,NaN,NaN
18,15,Neha,1700.90,20,2021-07-22,NaN,NaN,NaN,NaN,NaN

In [7]:
df_left['eno1'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
Name: eno1, dtype: bool

In [8]:
df_left[df_left['eno1'].isna()]

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
8,5,Jade,2000.00,10,2021-02-10,NaN,NaN,NaN,NaN,NaN
9,6,Smith,1000.00,10,2016-12-01,NaN,NaN,NaN,NaN,NaN
10,7,Robert,3000.00,20,2023-06-25,NaN,NaN,NaN,NaN,NaN
11,3,Nick,1000.00,30,2015-09-15,NaN,NaN,NaN,NaN,NaN
12,9,Naman,4000.00,30,2020-01-20,NaN,NaN,NaN,NaN,NaN
13,1,Vikas,1000.00,30,2017-10-03,NaN,NaN,NaN,NaN,NaN
14,11,Dennis,41000.00,20,2024-01-05,NaN,NaN,NaN,NaN,NaN
15,12,Karan,2200.00,20,2018-06-16,NaN,NaN,NaN,NaN,NaN
16,13,Simran,1500.89,10,2019-12-19,NaN,NaN,NaN,NaN,NaN
17,14,Amit,2000.00,30,2022-04-09,NaN,NaN,NaN,NaN,NaN
18,15,Neha,1700.90,20,2021-07-22,NaN,NaN,NaN,NaN,NaN

In [9]:
df_left[df_left['eno1'].notna()]

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,10,Amber,1000.0,10,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
1,2,Amar,1000.0,10,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
2,8,Sagar,1000.0,20,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
3,4,Thomas,1000.0,10,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
4,10,Amber,1000.0,10,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
5,2,Amar,1000.0,10,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
6,8,Sagar,1000.0,20,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
7,4,Thomas,1000.0,10,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18

In [10]:
df_right=df_emp.merge(df_Sal,left_on='eno',right_on='eno1',how='right')

In [11]:
df_right

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,10.0,Amber,1000.0,10.0,2018-05-14,10,Amber,1000,10,2018-05-14
1,10.0,Amber,1000.0,10.0,2018-05-14,10,Amber,1000,10,2018-05-14
2,2.0,Amar,1000.0,10.0,2017-03-22,2,Amar,1000,10,2017-03-22
3,2.0,Amar,1000.0,10.0,2017-03-22,2,Amar,1000,10,2017-03-22
4,8.0,Sagar,1000.0,20.0,2020-11-30,8,Sagar,1000,20,2020-11-30
5,8.0,Sagar,1000.0,20.0,2020-11-30,8,Sagar,1000,20,2020-11-30
6,4.0,Thomas,1000.0,10.0,2019-08-18,4,Thomas,1000,10,2019-08-18
7,4.0,Thomas,1000.0,10.0,2019-08-18,4,Thomas,1000,10,2019-08-18
8,NaN,NaN,NaN,NaN,NaN,95,Rakshith,1890,12,2019-08-18

In [12]:
df_right[df_right['eno'].isna()]

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
8,NaN,NaN,NaN,NaN,NaN,95,Rakshith,1890,12,2019-08-18

In [13]:
df_right[df_right['eno'].notna()]

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,10.0,Amber,1000.0,10.0,2018-05-14,10,Amber,1000,10,2018-05-14
1,10.0,Amber,1000.0,10.0,2018-05-14,10,Amber,1000,10,2018-05-14
2,2.0,Amar,1000.0,10.0,2017-03-22,2,Amar,1000,10,2017-03-22
3,2.0,Amar,1000.0,10.0,2017-03-22,2,Amar,1000,10,2017-03-22
4,8.0,Sagar,1000.0,20.0,2020-11-30,8,Sagar,1000,20,2020-11-30
5,8.0,Sagar,1000.0,20.0,2020-11-30,8,Sagar,1000,20,2020-11-30
6,4.0,Thomas,1000.0,10.0,2019-08-18,4,Thomas,1000,10,2019-08-18
7,4.0,Thomas,1000.0,10.0,2019-08-18,4,Thomas,1000,10,2019-08-18

In [14]:
df_outer=df_emp.merge(df_Sal,left_on='eno',right_on='eno1',how='outer')

In [15]:
df_outer

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,1.0,Vikas,1000.00,30.0,2017-10-03,NaN,NaN,NaN,NaN,NaN
1,2.0,Amar,1000.00,10.0,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
2,2.0,Amar,1000.00,10.0,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
3,3.0,Nick,1000.00,30.0,2015-09-15,NaN,NaN,NaN,NaN,NaN
4,4.0,Thomas,1000.00,10.0,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
5,4.0,Thomas,1000.00,10.0,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
6,5.0,Jade,2000.00,10.0,2021-02-10,NaN,NaN,NaN,NaN,NaN
7,6.0,Smith,1000.00,10.0,2016-12-01,NaN,NaN,NaN,NaN,NaN
8,7.0,Robert,3000.00,20.0,2023-06-25,NaN,NaN,NaN,NaN,NaN
9,8.0,Sagar,1000.00,20.0,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
10,8.0,Sagar,1000.00,20.0,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
11,9.0,Naman,4000.00,30.0,2020-01-20,NaN,NaN,NaN,NaN,NaN
12,10.0,Amber,1000.00,10.0,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
13,10.0,Amber,1000.00,10.0,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
14,11.0,Dennis,41000.00,20.0,2024-01-05,NaN,NaN,NaN,NaN,NaN
15,12.0,Karan,2200.00,20.0,2018-06-16,NaN,NaN,NaN,NaN,NaN
16,13.0,Simran,1500.89,10.0,2019-12-19,NaN,NaN,NaN,NaN,NaN
17,14.0,Amit,2000.00,30.0,2022-04-09,NaN,NaN,NaN,NaN,NaN
18,15.0,Neha,1700.90,20.0,2021-07-22,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,95.0,Rakshith,1890.0,12.0,2019-08-18

In [16]:
df_outer[(df_outer['eno'].isna()) | (df_outer['eno1'].isna())]

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
0,1.0,Vikas,1000.00,30.0,2017-10-03,NaN,NaN,NaN,NaN,NaN
3,3.0,Nick,1000.00,30.0,2015-09-15,NaN,NaN,NaN,NaN,NaN
6,5.0,Jade,2000.00,10.0,2021-02-10,NaN,NaN,NaN,NaN,NaN
7,6.0,Smith,1000.00,10.0,2016-12-01,NaN,NaN,NaN,NaN,NaN
8,7.0,Robert,3000.00,20.0,2023-06-25,NaN,NaN,NaN,NaN,NaN
11,9.0,Naman,4000.00,30.0,2020-01-20,NaN,NaN,NaN,NaN,NaN
14,11.0,Dennis,41000.00,20.0,2024-01-05,NaN,NaN,NaN,NaN,NaN
15,12.0,Karan,2200.00,20.0,2018-06-16,NaN,NaN,NaN,NaN,NaN
16,13.0,Simran,1500.89,10.0,2019-12-19,NaN,NaN,NaN,NaN,NaN
17,14.0,Amit,2000.00,30.0,2022-04-09,NaN,NaN,NaN,NaN,NaN
18,15.0,Neha,1700.90,20.0,2021-07-22,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,95.0,Rakshith,1890.0,12.0,2019-08-18

In [17]:
df_outer[(df_outer['eno'].notna()) & (df_outer['eno1'].notna())]

,eno,ename_x,salary_x,deptno_x,doj_x,eno1,ename_y,salary_y,deptno_y,doj_y
1,2.0,Amar,1000.0,10.0,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
2,2.0,Amar,1000.0,10.0,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
4,4.0,Thomas,1000.0,10.0,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
5,4.0,Thomas,1000.0,10.0,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
9,8.0,Sagar,1000.0,20.0,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
10,8.0,Sagar,1000.0,20.0,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
12,10.0,Amber,1000.0,10.0,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
13,10.0,Amber,1000.0,10.0,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14

In [18]:
df_outer.to_csv('outer_join_results.csv',index=False)

In [19]:
df_emp

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4    10   Amber   1000.00      10  2018-05-14
5     2    Amar   1000.00      10  2017-03-22
6     8   Sagar   1000.00      20  2020-11-30
7     4  Thomas   1000.00      10  2019-08-18
8     5    Jade   2000.00      10  2021-02-10
9     6   Smith   1000.00      10  2016-12-01
10    7  Robert   3000.00      20  2023-06-25
11    3    Nick   1000.00      30  2015-09-15
12    9   Naman   4000.00      30  2020-01-20
13    1   Vikas   1000.00      30  2017-10-03
14   11  Dennis  41000.00      20  2024-01-05
15   12   Karan   2200.00      20  2018-06-16
16   13  Simran   1500.89      10  2019-12-19
17   14    Amit   2000.00      30  2022-04-09
18   15    Neha   1700.90      20  2021-07-22

In [20]:
df_Sal

   eno1     ename  salary  deptno         doj
0    10     Amber    1000      10  2018-05-14
1     2      Amar    1000      10  2017-03-22
2     8     Sagar    1000      20  2020-11-30
3     4    Thomas    1000      10  2019-08-18
4    95  Rakshith    1890      12  2019-08-18

In [21]:
pd.concat([df_emp,df_Sal],axis=0)

     eno     ename    salary  deptno         doj  eno1
0   10.0     Amber   1000.00      10  2018-05-14   NaN
1    2.0      Amar   1000.00      10  2017-03-22   NaN
2    8.0     Sagar   1000.00      20  2020-11-30   NaN
3    4.0    Thomas   1000.00      10  2019-08-18   NaN
4   10.0     Amber   1000.00      10  2018-05-14   NaN
5    2.0      Amar   1000.00      10  2017-03-22   NaN
6    8.0     Sagar   1000.00      20  2020-11-30   NaN
7    4.0    Thomas   1000.00      10  2019-08-18   NaN
8    5.0      Jade   2000.00      10  2021-02-10   NaN
9    6.0     Smith   1000.00      10  2016-12-01   NaN
10   7.0    Robert   3000.00      20  2023-06-25   NaN
11   3.0      Nick   1000.00      30  2015-09-15   NaN
12   9.0     Naman   4000.00      30  2020-01-20   NaN
13   1.0     Vikas   1000.00      30  2017-10-03   NaN
14  11.0    Dennis  41000.00      20  2024-01-05   NaN
15  12.0     Karan   2200.00      20  2018-06-16   NaN
16  13.0    Simran   1500.89      10  2019-12-19   NaN
17  14.0      Amit   2000.00      30  2022-04-09   NaN
18  15.0      Neha   1700.90      20  2021-07-22   NaN
0    NaN     Amber   1000.00      10  2018-05-14  10.0
1    NaN      Amar   1000.00      10  2017-03-22   2.0
2    NaN     Sagar   1000.00      20  2020-11-30   8.0
3    NaN    Thomas   1000.00      10  2019-08-18   4.0
4    NaN  Rakshith   1890.00      12  2019-08-18  95.0

In [22]:
pd.concat([df_emp,df_Sal],axis=1)

,eno,ename,salary,deptno,doj,eno1,ename,salary,deptno,doj
0,10,Amber,1000.00,10,2018-05-14,10.0,Amber,1000.0,10.0,2018-05-14
1,2,Amar,1000.00,10,2017-03-22,2.0,Amar,1000.0,10.0,2017-03-22
2,8,Sagar,1000.00,20,2020-11-30,8.0,Sagar,1000.0,20.0,2020-11-30
3,4,Thomas,1000.00,10,2019-08-18,4.0,Thomas,1000.0,10.0,2019-08-18
4,10,Amber,1000.00,10,2018-05-14,95.0,Rakshith,1890.0,12.0,2019-08-18
5,2,Amar,1000.00,10,2017-03-22,NaN,NaN,NaN,NaN,NaN
6,8,Sagar,1000.00,20,2020-11-30,NaN,NaN,NaN,NaN,NaN
7,4,Thomas,1000.00,10,2019-08-18,NaN,NaN,NaN,NaN,NaN
8,5,Jade,2000.00,10,2021-02-10,NaN,NaN,NaN,NaN,NaN
9,6,Smith,1000.00,10,2016-12-01,NaN,NaN,NaN,NaN,NaN
10,7,Robert,3000.00,20,2023-06-25,NaN,NaN,NaN,NaN,NaN
11,3,Nick,1000.00,30,2015-09-15,NaN,NaN,NaN,NaN,NaN
12,9,Naman,4000.00,30,2020-01-20,NaN,NaN,NaN,NaN,NaN
13,1,Vikas,1000.00,30,2017-10-03,NaN,NaN,NaN,NaN,NaN
14,11,Dennis,41000.00,20,2024-01-05,NaN,NaN,NaN,NaN,NaN
15,12,Karan,2200.00,20,2018-06-16,NaN,NaN,NaN,NaN,NaN
16,13,Simran,1500.89,10,2019-12-19,NaN,NaN,NaN,NaN,NaN
17,14,Amit,2000.00,30,2022-04-09,NaN,NaN,NaN,NaN,NaN
18,15,Neha,1700.90,20,2021-07-22,NaN,NaN,NaN,NaN,NaN

In [23]:
pd.concat([df_emp,df_Sal],axis=0,join='outer')

     eno     ename    salary  deptno         doj  eno1
0   10.0     Amber   1000.00      10  2018-05-14   NaN
1    2.0      Amar   1000.00      10  2017-03-22   NaN
2    8.0     Sagar   1000.00      20  2020-11-30   NaN
3    4.0    Thomas   1000.00      10  2019-08-18   NaN
4   10.0     Amber   1000.00      10  2018-05-14   NaN
5    2.0      Amar   1000.00      10  2017-03-22   NaN
6    8.0     Sagar   1000.00      20  2020-11-30   NaN
7    4.0    Thomas   1000.00      10  2019-08-18   NaN
8    5.0      Jade   2000.00      10  2021-02-10   NaN
9    6.0     Smith   1000.00      10  2016-12-01   NaN
10   7.0    Robert   3000.00      20  2023-06-25   NaN
11   3.0      Nick   1000.00      30  2015-09-15   NaN
12   9.0     Naman   4000.00      30  2020-01-20   NaN
13   1.0     Vikas   1000.00      30  2017-10-03   NaN
14  11.0    Dennis  41000.00      20  2024-01-05   NaN
15  12.0     Karan   2200.00      20  2018-06-16   NaN
16  13.0    Simran   1500.89      10  2019-12-19   NaN
17  14.0      Amit   2000.00      30  2022-04-09   NaN
18  15.0      Neha   1700.90      20  2021-07-22   NaN
0    NaN     Amber   1000.00      10  2018-05-14  10.0
1    NaN      Amar   1000.00      10  2017-03-22   2.0
2    NaN     Sagar   1000.00      20  2020-11-30   8.0
3    NaN    Thomas   1000.00      10  2019-08-18   4.0
4    NaN  Rakshith   1890.00      12  2019-08-18  95.0

In [24]:
pd.concat([df_emp,df_Sal],axis=0).drop_duplicates(keep=False)

     eno     ename    salary  deptno         doj  eno1
8    5.0      Jade   2000.00      10  2021-02-10   NaN
9    6.0     Smith   1000.00      10  2016-12-01   NaN
10   7.0    Robert   3000.00      20  2023-06-25   NaN
11   3.0      Nick   1000.00      30  2015-09-15   NaN
12   9.0     Naman   4000.00      30  2020-01-20   NaN
13   1.0     Vikas   1000.00      30  2017-10-03   NaN
14  11.0    Dennis  41000.00      20  2024-01-05   NaN
15  12.0     Karan   2200.00      20  2018-06-16   NaN
16  13.0    Simran   1500.89      10  2019-12-19   NaN
17  14.0      Amit   2000.00      30  2022-04-09   NaN
18  15.0      Neha   1700.90      20  2021-07-22   NaN
0    NaN     Amber   1000.00      10  2018-05-14  10.0
1    NaN      Amar   1000.00      10  2017-03-22   2.0
2    NaN     Sagar   1000.00      20  2020-11-30   8.0
3    NaN    Thomas   1000.00      10  2019-08-18   4.0
4    NaN  Rakshith   1890.00      12  2019-08-18  95.0

In [25]:
df_emp.duplicated()

0     False
1     False
2     False
3     False
4      True
5      True
6      True
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
dtype: bool

In [26]:
df_emp[df_emp.duplicated()]

   eno   ename  salary  deptno         doj
4   10   Amber  1000.0      10  2018-05-14
5    2    Amar  1000.0      10  2017-03-22
6    8   Sagar  1000.0      20  2020-11-30
7    4  Thomas  1000.0      10  2019-08-18

In [27]:
df_emp[~df_emp.duplicated()]

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
8     5    Jade   2000.00      10  2021-02-10
9     6   Smith   1000.00      10  2016-12-01
10    7  Robert   3000.00      20  2023-06-25
11    3    Nick   1000.00      30  2015-09-15
12    9   Naman   4000.00      30  2020-01-20
13    1   Vikas   1000.00      30  2017-10-03
14   11  Dennis  41000.00      20  2024-01-05
15   12   Karan   2200.00      20  2018-06-16
16   13  Simran   1500.89      10  2019-12-19
17   14    Amit   2000.00      30  2022-04-09
18   15    Neha   1700.90      20  2021-07-22

In [34]:
df=pd.read_csv('pandayday1\\emp1.csv')
df

    eno   ename    salary  deptno         doj
0    10   Amber   1000.00      10  2018-05-14
1     2    Amar   1000.00      10  2017-03-22
2     8   Sagar   1000.00      20  2020-11-30
3     4  Thomas   1000.00      10  2019-08-18
4    10   Amber   1000.00      10  2018-05-14
5     2    Amar   1000.00      10  2017-03-22
6     8   Sagar   1000.00      20  2020-11-30
7     4  Thomas   1000.00      10  2019-08-18
8     5    Jade   2000.00      10  2021-02-10
9     6   Smith   1000.00      10  2016-12-01
10    7  Robert   3000.00      20  2023-06-25
11    3    Nick   1000.00      30  2015-09-15
12    9   Naman   4000.00      30  2020-01-20
13    1   Vikas   1000.00      30  2017-10-03
14   11  Dennis  41000.00      20  2024-01-05
15   12   Karan   2200.00      20  2018-06-16
16   13  Simran   1500.89      10  2019-12-19
17   14    Amit   2000.00      30  2022-04-09
18   15    Neha   1700.90      20  2021-07-22

In [29]:
df_group=df.groupby('ename')['eno'].count()
df_group

ename
Amar      2
Amber     2
Amit      1
Dennis    1
Jade      1
Karan     1
Naman     1
Neha      1
Nick      1
Robert    1
Sagar     2
Simran    1
Smith     1
Thomas    2
Vikas     1
Name: eno, dtype: int64

In [30]:
type(df_group)

pandas.Series

In [31]:
df_group=df.groupby('ename',as_index=False)['eno'].count()
df_group.rename(columns={'eno':'count_eno'})

     ename  count_eno
0     Amar          2
1    Amber          2
2     Amit          1
3   Dennis          1
4     Jade          1
5    Karan          1
6    Naman          1
7     Neha          1
8     Nick          1
9   Robert          1
10   Sagar          2
11  Simran          1
12   Smith          1
13  Thomas          2
14   Vikas          1

In [32]:
df_group

     ename  eno
0     Amar    2
1    Amber    2
2     Amit    1
3   Dennis    1
4     Jade    1
5    Karan    1
6    Naman    1
7     Neha    1
8     Nick    1
9   Robert    1
10   Sagar    2
11  Simran    1
12   Smith    1
13  Thomas    2
14   Vikas    1