In [5]:
data={'empno':[1,2,3,4,5],'ename':['rakshi','keshav','shiva','adarsh','keerthi'],'deptno':['HR','IT','Chemist','Pysics','Biology'],'salary':[1000,2000,3000,4000,500]}

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame(data)

In [28]:
df

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500

In [29]:
df_excel=df.to_excel('employee1.xlsx',index=False,sheet_name='employee1')

In [30]:
pd.read_excel('employee1.xlsx',sheet_name='employee1')

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500

In [31]:
df_json=df.to_json('employee3.json',orient='records',indent=4)

In [32]:
pd.read_json('employee3.json')

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500

In [38]:
#df_parquet=df.to_parquet('employee6.parquet',index=False,engine='pyarrow')

In [40]:
#pd.read_parquet('employee4.parquet')

In [42]:
#database connection
from sqlalchemy import create_engine
from urllib.parse import quote_plus
password=quote_plus('143#bujju')
conn_mysql=create_engine(f"mysql+pymysql://root:{password}@localhost:3306/ETL_Automation1")

In [44]:
df_mysql1=df.to_sql('employee4_sql',conn_mysql,index=False)

In [45]:
pd.read_sql('select * from employee4_sql',conn_mysql)

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500

In [64]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import oracledb

In [57]:
password=quote_plus('admin')
conn_oracle=create_engine('oracle+oracledb://system:admin@localhost:1521/xe')
# df_oracle=df.to_sql('employeee2',conn_oracle,index=False)

In [81]:
query='select * from employeee2'
pd.read_sql(query,conn_oracle)

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500

In [83]:
df_excel1=pd.read_excel('employee1.xlsx',sheet_name='employee1')

In [9]:
df_parquet=df.to_parquet('employee_jun.parquet',index=False,engine='pyarrow')

In [10]:
pd.read_parquet('employee_jun.parquet')

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500

In [11]:
df_excel1=pd.read_excel('employee1.xlsx',sheet_name='employee1')

In [13]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import oracledb

In [14]:
password=quote_plus('143#bujju')
conn_mysql1=create_engine(f"mysql+pymysql://root:{password}@localhost:3306/ETL_Automation1")

In [25]:
df_db=pd.read_sql('select * from employee1_sql',conn_mysql1)
df_db

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500
5     90     agni       50  100000

In [23]:
pd.merge(df_excel1,df_db,on='empno',how='inner')

   empno  ename_x deptno_x  salary_x  ename_y deptno_y  salary_y
0      1   rakshi       HR      1000   rakshi       HR      1000
1      2   keshav       IT      2000   keshav       IT      2000
2      3    shiva  Chemist      3000    shiva  Chemist      3000
3      4   adarsh   Pysics      4000   adarsh   Pysics      4000
4      5  keerthi  Biology       500  keerthi  Biology       500

In [24]:
df_excel1.merge(df_db,on='empno',how='left')

   empno  ename_x deptno_x  salary_x  ename_y deptno_y  salary_y
0      1   rakshi       HR      1000   rakshi       HR      1000
1      2   keshav       IT      2000   keshav       IT      2000
2      3    shiva  Chemist      3000    shiva  Chemist      3000
3      4   adarsh   Pysics      4000   adarsh   Pysics      4000
4      5  keerthi  Biology       500  keerthi  Biology       500

In [36]:
df_right=df_excel1.merge(df_db,on='empno',how='right')

In [37]:
df_right

   empno  ename_x deptno_x  salary_x  ename_y deptno_y  salary_y
0      1   rakshi       HR    1000.0   rakshi       HR      1000
1      2   keshav       IT    2000.0   keshav       IT      2000
2      3    shiva  Chemist    3000.0    shiva  Chemist      3000
3      4   adarsh   Pysics    4000.0   adarsh   Pysics      4000
4      5  keerthi  Biology     500.0  keerthi  Biology       500
5     90      NaN      NaN       NaN     agni       50    100000

In [38]:
df_right['ename_x'].isna()

0    False
1    False
2    False
3    False
4    False
5     True
Name: ename_x, dtype: bool

In [39]:
df_right[df_right['ename_x'].isna()]

   empno ename_x deptno_x  salary_x ename_y deptno_y  salary_y
5     90     NaN      NaN       NaN    agni       50    100000

In [40]:
df_excel1=pd.read_excel('employee1.xlsx',sheet_name='employee1')

In [41]:
df_db=pd.read_sql('select * from employee1_sql',conn_mysql1)
df_db

   empno    ename   deptno  salary
0      1   rakshi       HR    1000
1      2   keshav       IT    2000
2      3    shiva  Chemist    3000
3      4   adarsh   Pysics    4000
4      5  keerthi  Biology     500
5     90     agni       50  100000

In [44]:
df_excel1['empno']

0    1
1    2
2    3
3    4
4    5
Name: empno, dtype: int64

In [45]:
df_db['empno']

0     1
1     2
2     3
3     4
4     5
5    90
Name: empno, dtype: int64

In [47]:
df_db['empno'].isin(df_excel1['empno'])

0     True
1     True
2     True
3     True
4     True
5    False
Name: empno, dtype: bool

In [50]:
df_result=~df_db['empno'].isin(df_excel1['empno'])

In [51]:
df_result

0    False
1    False
2    False
3    False
4    False
5     True
Name: empno, dtype: bool

In [52]:
df_db[df_result]

   empno ename deptno  salary
5     90  agni     50  100000

In [54]:
df_sql=pd.read_sql('select * from employee1_sql',conn_mysql1)

In [59]:
query='select * from employeee2'
df_oracl=pd.read_sql(query,conn_oracle)

In [61]:
pd.merge(df_sql,df_oracl,on='empno',how='left')

   empno  ename_x deptno_x  salary_x  ename_y deptno_y  salary_y
0      1   rakshi       HR      1000   rakshi       HR    1000.0
1      2   keshav       IT      2000   keshav       IT    2000.0
2      3    shiva  Chemist      3000    shiva  Chemist    3000.0
3      4   adarsh   Pysics      4000   adarsh   Pysics    4000.0
4      5  keerthi  Biology       500  keerthi  Biology     500.0
5     90     agni       50    100000      NaN      NaN       NaN
6     95    Navya       55      2000      NaN      NaN       NaN